apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: db-secrets
spec:
  backendType: systemManager
  region: ap-southeast-1
  data:
    - key: sarge.DB_DATABASE
      name: DATABASE
    - key: sarge.DB_HOST
      name: HOST
    - key: sarge.DB_USERNAME
      name: USERNAME
    - key: sarge.DB_PASSWORD
      name: PASSWORD
