AWSTemplateFormatVersion: 2010-09-09

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "SSH CIDR"
        Parameters:
          - SSHLocation


Description: This template creates the necessary Security Groups

Parameters:
  SSHLocation:
    AllowedPattern:  '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
    Default: 0.0.0.0/0
    Description: The IP Address range that can be used to access the web server using SSH.
    MaxLength: '18'
    MinLength: '9'
    Type: String

Resources:
  # Create Beanstalk ALB Security Group
  BeanstalkALBSG:
  Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for BeanStalk Application on port 80/443
      GroupName: BeanstalkALBSG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: BeanstalkALBSG
        - Key: Tier
          Beginner Challenge

      VpcId: !ImportValue
