AWSTemplateFormatVersion: 2010-09-09

Description: Common template for provisioning resources needed for the Challenges

Resources:
  SargePyPlate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: pyplate.yaml
  SargeVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc.yaml
    DependsOn: SargePyPlate
  SargeRDSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - SargePyPlate
      - SargeVPCStack
    Properties:
      TemplateURL: rds.yaml
      Parameters:
        DBAppCIDRs:
          Fn::Join: 
            - ','
            -
              - Fn::GetAtt:
                - SargeVPCStack
                - Outputs.PrivateSubnetACDIR
              - Fn::GetAtt:
                - SargeVPCStack
                - Outputs.PrivateSubnetBCDIR
        VPCId:
          Fn::GetAtt:
          - SargeVPCStack
          - Outputs.VPCId
        DBSubnetGroupIDs:
          Fn::Join:
            - ','
            -
              - Fn::GetAtt:
                - SargeVPCStack
                - Outputs.DatabaseSubnetA
              - Fn::GetAtt:
                - SargeVPCStack
                - Outputs.DatabaseSubnetB
