AWSTemplateFormatVersion: 2010-09-09

Resources:
  SargeVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc.yaml
  SargeRDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: rds.yaml
      Parameters:
        DBAppCIDRs:
          Fn::Join: 
            - ','
            -
              - Fn::GetAtt:
                - SargeVPCStack
                - Outputs.PrivateSubnetACDIR
              - Fn::GetAtt:
                - SargeVPCStack
                - Outputs.PrivateSubnetBCDIR
        VPCId:
          Fn::GetAtt:
          - SargeVPCStack
          - Outputs.VPCId
        DBSubnetGroupIDs:
          Fn::Join:
            - ','
            -
              - Fn::GetAtt:
                - SargeVPCStack
                - Outputs.DatabaseSubnetA
              - Fn::GetAtt:
                - SargeVPCStack
                - Outputs.DatabaseSubnetB
