AWSTemplateFormatVersion: 2010-09-09

Description: Common template for provisioning resources needed for the Challenges

Parameters:
  SubdomainPrefix:
    Default: sarge
    Description: Please enter the subdomain prefix
    Type: String

Resources:
  SargePyPlate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: pyplate.yaml
  SargeCertificates:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: certificates.yaml
      Parameters:
        SubdomainPrefix: !Ref SubdomainPrefix
  SargeVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc.yaml
    DependsOn: SargePyPlate
  SargeRDSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - SargePyPlate
      - SargeVPCStack
    Properties:
      TemplateURL: rds.yaml
      Parameters:
        DBAppCIDRs:
          Fn::Join: 
            - ','
            -
              - Fn::GetAtt:
                - SargeVPCStack
                - Outputs.PrivateSubnetACDIR
              - Fn::GetAtt:
                - SargeVPCStack
                - Outputs.PrivateSubnetBCDIR
        VPCId:
          Fn::GetAtt:
          - SargeVPCStack
          - Outputs.VPCId
        DBSubnetGroupIDs:
          Fn::Join:
            - ','
            -
              - Fn::GetAtt:
                - SargeVPCStack
                - Outputs.DatabaseSubnetA
              - Fn::GetAtt:
                - SargeVPCStack
                - Outputs.DatabaseSubnetB
  SargeEBTierOneStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - SargePyPlate
      - SargeVPCStack
      - SargeRDSStack
    Properties:
      TemplateURL: tier1/beanstalk.yaml
      Parameters:
        VPCId:
          Fn::GetAtt:
          - SargeVPCStack
          - Outputs.VPCId
        PublicCIDRs:
          Fn::Join:
            - ','
            -
              - Fn::GetAtt:
                - SargeVPCStack
                - Outputs.PublicSubnetACDIR
              - Fn::GetAtt:
                - SargeVPCStack
                - Outputs.PublicSubnetBCDIR
        PublicSubnets:
          Fn::Join:
            - ','
            -
              - Fn::GetAtt:
                - SargeVPCStack
                - Outputs.PublicSubnetA
              - Fn::GetAtt:
                - SargeVPCStack
                - Outputs.PublicSubnetB
        PrivateSubnets:
          Fn::Join:
            - ','
            -
              - Fn::GetAtt:
                - SargeVPCStack
                - Outputs.PrivateSubnetA
              - Fn::GetAtt:
                - SargeVPCStack
                - Outputs.PrivateSubnetB
