AWSTemplateFormatVersion: 2010-09-09

Description: This templates provisions ssl certificates via Certificate Manager

Parameters:
  DomainName:
    Default: sarge-tier1.apperdevops.com
    Description: Please enter Domain name
    Type: String

Resources:
  SargeCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
        DomainName: !Ref DomainName
        ValidationMethod: DNS

Outputs:
  Cert:
    Description: The Created Certificate
    Value: !Ref SargeCertificate
    Export:
      Name:
        'Fn::Sub': '${AWS::StackName}-Cert'
