apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: sarge-express-miniapp
  name: sarge-express-miniapp
spec:
  ports:
  - name: "http-sarge-express-miniapp-port"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: sarge-express-miniapp
